title: ë§¨ì˜¤ë¸Œí”¼ìŠ¤ ì¼ê¸°ì¥ ğŸ‡°ğŸ‡·ğŸ‡©ğŸ‡ª
logo: /assets/img/logo.jpg
description: ë§¤ì¼ ì“°ëŠ” ê°œì¸ ì¼ê¸°ì¥.
show_downloads: false
google_analytics: UA-120539302-1
theme: jekyll-theme-minimal
plugins:
  - jekyll-redirect-from
