title: ë§¨ì˜¤ë¸Œë‹¤ì´ì–´ë¦¬
logo: <a href="https://manofpeace1.github.io/manofdiary/">/assets/img/avatar.jpg</a>
description: <span id=white>_</span>ğŸ’» <a href="https://play.google.com/store/apps/developer?id=Manof+Studios">ğŸ“±</a> ğŸ‡°ğŸ‡·ğŸ‡©ğŸ‡ª <span id=marvel>MARVEL</span> <a href="https://my.playstation.com/profile/manofpeace0/trophies">ğŸ®</a>
show_downloads: false
google_analytics: UA-120539302-1
theme: jekyll-theme-minimal
