title:
logo: /assets/img/avatar.jpg
description: ğŸ’» ğŸ‡°ğŸ‡·ğŸ‡©ğŸ‡ª MARVEL <a href="http://www.google.com">ğŸ®</a>
show_downloads: false
google_analytics: UA-120539302-1
theme: jekyll-theme-minimal
